name: Daily GitHub Commit

on:
  schedule:
    - cron: "0 11 * * *" # Runs every day at 11:00 UTC = 12:00 BST
  workflow_dispatch: # Allows you to trigger manually if needed

jobs:
  auto-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: List repo contents
        run: ls -la
        working-directory: ${{ github.workspace }}

      - name: Configure Git identity
        run: |
          git config --global user.name "HSandles"
          git config --global user.email "hesandles@gmail.com"

      - name: Run daily commit script
        run: python daily_commit.py
        working-directory: ${{ github.workspace }}
