name: Daily GitHub Commit

on:
  schedule:
    - cron: "0 11 * * *" # Runs every day at 11:00 UTC = 12:00 BST
  workflow_dispatch: # Allows you to trigger manually if needed

jobs:
  auto-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: List repo contents
        run: ls -la
        working-directory: ${{ github.workspace }}

      - name: Configure Git identity
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Run daily commit script
        run: python daily_commit.py
        working-directory: ${{ github.workspace }}

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add daily_commit.txt
          git commit -m "$(shuf -n1 -e \
            "Refactored for future-proofing" \
            "Daily grind begins" \
            "Added legacy support for dinosaurs" \
            "Optimised coffee consumption" \
            "Deleted 400 lines of bad code" \
            "Moved a div, felt alive" \
            "This one’s for the green square" \
            "Refactored the refactor" \
            "Commented out the chaos" \
            "Ctrl+C, Ctrl+V excellence")"
          git push
